require('dotenv').config();

export const ENV_READER = {
    EMULATOR_DEVICE1_NAME: process.env.EMULATOR_DEVICE1_NAME,
    EMULATOR_DEVICE1_ID: process.env.EMULATOR_DEVICE1_ID,
    EMULATOR_DEVICE1_VERSION: process.env.EMULATOR_DEVICE1_VERSION,

    EMULATOR_DEVICE2_NAME: process.env.EMULATOR_DEVICE2_NAME,
    EMULATOR_DEVICE2_ID: process.env.EMULATOR_DEVICE2_ID,
    EMULATOR_DEVICE2_VERSION: process.env.EMULATOR_DEVICE2_VERSION,

    BROWSERSTACK_ANDROID_DEVICE: process.env.BROWSERSTACK_ANDROID_DEVICE,
    BROWSERSTACK_ANDROID_VERSION: process.env.BROWSERSTACK_ANDROID_VERSION,
    BROWSERSTACK_ANDROID_APP_ID: process.env.BROWSERSTACK_ANDROID_APP_ID,

    BROWSERSTACK_IOS_DEVICE: process.env.BROWSERSTACK_IOS_DEVICE,
    BROWSERSTACK_IOS_VERSION: process.env.BROWSERSTACK_IOS_VERSION,
    BROWSERSTACK_IOS_APP_ID: process.env.BROWSERSTACK_IOS_APP_ID,

    BROWSERSTACK_USERNAME: process.env.BROWSERSTACK_USERNAME,
    BROWSERSTACK_ACCESS_KEY: process.env.BROWSERSTACK_ACCESS_KEY,
}